development: &non_production_settings
  site_url: http://localhost:3000
  site_name: Siva
  admin_email: admin@siva.ir
  
test:
  <<: *non_production_settings

staging:
  site_url: http://staging.example.com
  site_name: Siva
  admin_email: admin@siva.ir
  
production:
  site_url: http://www.example.com
  site_name: Siva
  admin_email: admin@siva.ir
